import type { SourceCatalogEntry } from "./source-types";

export const sourceCatalog: SourceCatalogEntry[] = [
  {
    id: "official-openai-news",
    label: "OpenAI Newsroom",
    class: "official",
    transport: "rss",
    tier: "structured",
    enabledByDefault: true,
    locale: "en",
    url: "https://openai.com/news/rss.xml",
    mappingMode: "observe_only",
    maxItems: 14,
    topicHints: ["ai agents", "workflow automation", "customer support", "developer tools"],
    sourceType: "COMPANY_UPDATE"
  },
  {
    id: "official-anthropic-news",
    label: "Anthropic News",
    class: "official",
    transport: "html",
    tier: "manual_html",
    enabledByDefault: false,
    locale: "en",
    url: "https://www.anthropic.com/news",
    mappingMode: "observe_only",
    maxItems: 4,
    sourceType: "COMPANY_UPDATE"
  },
  {
    id: "official-google-deepmind-blog",
    label: "Google DeepMind Blog",
    class: "official",
    transport: "html",
    tier: "manual_html",
    enabledByDefault: false,
    locale: "en",
    url: "https://deepmind.google/discover/blog/",
    mappingMode: "observe_only",
    maxItems: 4,
    sourceType: "COMPANY_UPDATE"
  },
  {
    id: "official-hugging-face-blog",
    label: "Hugging Face Blog",
    class: "official",
    transport: "rss",
    tier: "structured",
    enabledByDefault: true,
    locale: "en",
    url: "https://huggingface.co/blog/feed.xml",
    mappingMode: "observe_only",
    maxItems: 12,
    topicHints: ["open models", "model evaluation", "developer tooling", "agent workflows"],
    sourceType: "COMPANY_UPDATE"
  },
  {
    id: "official-github-ai-ml",
    label: "GitHub Blog AI & ML",
    class: "official",
    transport: "html",
    tier: "manual_html",
    enabledByDefault: true,
    locale: "en",
    url: "https://github.blog/ai-and-ml/",
    mappingMode: "observe_only",
    maxItems: 12,
    topicHints: ["developer tools", "coding assistants", "workflow automation", "copilots"],
    sourceType: "COMPANY_UPDATE"
  },
  {
    id: "official-microsoft-ai",
    label: "Microsoft Source AI",
    class: "official",
    transport: "html",
    tier: "manual_html",
    enabledByDefault: true,
    locale: "en",
    url: "https://news.microsoft.com/source/topics/ai/",
    mappingMode: "observe_only",
    maxItems: 12,
    topicHints: ["enterprise ai", "workflow automation", "copilots", "productivity tools"],
    sourceType: "COMPANY_UPDATE"
  },
  {
    id: "official-cohere-blog",
    label: "Cohere Blog",
    class: "official",
    transport: "html",
    tier: "manual_html",
    enabledByDefault: false,
    locale: "en",
    url: "https://cohere.com/blog",
    mappingMode: "observe_only",
    maxItems: 8,
    sourceType: "COMPANY_UPDATE"
  },
  {
    id: "official-mistral-news",
    label: "Mistral AI News",
    class: "official",
    transport: "html",
    tier: "manual_html",
    enabledByDefault: false,
    locale: "en",
    url: "https://mistral.ai/news",
    mappingMode: "observe_only",
    maxItems: 4,
    sourceType: "COMPANY_UPDATE"
  },
  {
    id: "media-the-decoder-ai",
    label: "The Decoder",
    class: "media",
    transport: "html",
    tier: "manual_html",
    enabledByDefault: true,
    locale: "en",
    url: "https://the-decoder.com/",
    mappingMode: "observe_only",
    maxItems: 10,
    topicHints: ["model launches", "agent tooling", "enterprise adoption", "productivity"],
    sourceType: "NEWS"
  },
  {
    id: "media-36kr-tech",
    label: "36氪",
    class: "media",
    transport: "rss",
    tier: "structured",
    enabledByDefault: true,
    locale: "zh",
    url: "https://36kr.com/feed",
    mappingMode: "observe_only",
    maxItems: 14,
    topicHints: ["ai agents", "enterprise adoption", "automation", "productivity tools"],
    sourceType: "NEWS"
  },
  {
    id: "media-geekpark",
    label: "极客公园",
    class: "media",
    transport: "rss",
    tier: "structured",
    enabledByDefault: false,
    locale: "zh",
    url: "http://www.geekpark.net/rss",
    mappingMode: "observe_only",
    maxItems: 12,
    topicHints: ["ai products", "developer tools", "enterprise software", "automation"],
    sourceType: "NEWS"
  },
  {
    id: "media-ifanr",
    label: "爱范儿",
    class: "media",
    transport: "rss",
    tier: "structured",
    enabledByDefault: true,
    locale: "zh",
    url: "https://www.ifanr.com/feed",
    mappingMode: "observe_only",
    maxItems: 14,
    topicHints: ["consumer ai", "productivity", "devices", "ai products"],
    sourceType: "NEWS"
  },
  {
    id: "media-huxiu",
    label: "虎嗅",
    class: "media",
    transport: "rss",
    tier: "structured",
    enabledByDefault: false,
    locale: "zh",
    url: "https://rss.huxiu.com/",
    mappingMode: "observe_only",
    maxItems: 12,
    topicHints: ["enterprise ai", "automation", "industry adoption", "business software"],
    sourceType: "NEWS"
  },
  {
    id: "jobs-openai-careers",
    label: "OpenAI Careers",
    class: "jobs",
    transport: "html",
    tier: "manual_html",
    enabledByDefault: false,
    locale: "en",
    url: "https://openai.com/jobs/",
    mappingMode: "direct_mapped",
    roleSlug: "bookkeeping-clerk",
    sourceType: "JOB_POSTING"
  },
  // Jobs sources remain manual watchlist entries and are routed through a dedicated
  // careers parser so the downstream classifier can keep them as lower-weight signals.
  {
    id: "jobs-anthropic-careers",
    label: "Anthropic Careers",
    class: "jobs",
    transport: "html",
    tier: "manual_html",
    enabledByDefault: false,
    locale: "en",
    url: "https://www.anthropic.com/careers",
    mappingMode: "direct_mapped",
    roleSlug: "industrial-maintenance-technician",
    sourceType: "JOB_POSTING"
  },
  {
    id: "media-techcrunch-ai",
    label: "TechCrunch AI",
    class: "media",
    transport: "rss",
    tier: "structured",
    enabledByDefault: true,
    locale: "en",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    mappingMode: "observe_only",
    maxItems: 14,
    topicHints: ["startup adoption", "enterprise software", "ai products", "funding"],
    sourceType: "NEWS"
  },
  {
    id: "media-venturebeat-ai",
    label: "VentureBeat AI",
    class: "media",
    transport: "rss",
    tier: "structured",
    enabledByDefault: true,
    locale: "en",
    url: "https://venturebeat.com/feed/",
    mappingMode: "observe_only",
    maxItems: 14,
    topicHints: ["enterprise ai", "ai infrastructure", "developer tools", "platform adoption"],
    sourceType: "NEWS"
  },
  {
    id: "media-jiqizhixin-ai",
    label: "机器之心",
    class: "media",
    transport: "rss",
    tier: "structured",
    enabledByDefault: false,
    locale: "zh",
    url: "https://www.jiqizhixin.com/rss",
    mappingMode: "observe_only",
    maxItems: 10,
    topicHints: ["ai agents", "model launches", "enterprise adoption", "research"],
    sourceType: "NEWS"
  },
  {
    id: "media-qbitai-ai",
    label: "量子位",
    class: "media",
    transport: "html",
    tier: "manual_html",
    enabledByDefault: true,
    locale: "zh",
    url: "https://www.qbitai.com/",
    mappingMode: "observe_only",
    maxItems: 10,
    topicHints: ["ai agents", "model launches", "enterprise adoption", "research"],
    sourceType: "NEWS"
  },
  {
    id: "media-aibase-ai",
    label: "AIbase",
    class: "media",
    transport: "html",
    tier: "manual_html",
    enabledByDefault: true,
    locale: "zh",
    url: "https://www.aibase.com/news/",
    mappingMode: "observe_only",
    maxItems: 10,
    topicHints: ["ai products", "platform adoption", "enterprise software", "automation"],
    sourceType: "NEWS"
  },
  // X/Twitter stays out of automated ingestion because it is noisy,
  // hard to reproduce, and brittle for a deterministic allowlist.
  {
    id: "media-infoq-ai-ml",
    label: "InfoQ AI/ML/Data Engineering",
    class: "media",
    transport: "html",
    tier: "manual_html",
    enabledByDefault: true,
    locale: "en",
    url: "https://www.infoq.com/ai-ml-data-eng/",
    mappingMode: "observe_only",
    maxItems: 10,
    topicHints: ["developer tools", "data engineering", "workflow automation", "enterprise adoption"],
    sourceType: "NEWS"
  }
];
